using System.Collections.Generic;
using System.Linq;

public static class GSC_StoryScript
{
    //public static List<GSC_SceneUnit> GetIntro()
    //{
    //    return GSC_StoryFactory.Create()
    //    .WithChapter("")
    //    .WithScene(0)
    //    .WithShowImage("Intro", "Logo", "Background", 1, 2f, 5f)
    //    .WithContainer("ShowMainMenu")
    //    .WithParameter("Fade", 1f)
    //    .Build().Chapters[0].Scenes.ToList();
    //}

    //public static GSC_StoryUnit GetStory()
    //{
    //    return GSC_StoryFactory.Create()
    //        .WithChapter("Why we live our lives?", "")
    //        .WithScene(0)
    //        .WithShowImage("Chapter 01", "Frame 01", "Background", 1, 1f, 2f)
    //        .WithShowImage("Chapter 01", "Frame 02", "Background", 1, 1f, 2f)
    //        .WithShowImage("Chapter 01", "Frame 03", "Background", 1, 1f, 0f)
    //        .WithContainer("ShowDialogue")
    //        .WithParameter("Character", "Player")
    //        .WithParameter("Dialogue", "Hello, dear. I'm home.")
    //        .WithParameter("Append", false).WithParameter("Duration", 2f).WithParameter("Fade", 1f).WithParameter("WaitToComplete", true)
    //        .WithShowImage("Chapter 01", "Frame 04", "Background", 1, 1f, 0f)
        
      
    //    .WithParameter("Character", "Aisley")
    //    .WithParameter("Dialogue", "How was your day at work?")
    //    .WithParameter("Append", false)
    //    .WithParameter("Duration", 2f)
    //    .WithParameter("Fade", 1f)
    //    .WithParameter("WaitToComplete", true)
    //    .WithContainer("ShowImage")
    //    .WithParameter("SpriteGroup", "Chapter 01")
    //    .WithParameter("SpriteName", "Frame 06")
    //    .WithParameter("Controller", "Background")
    //    .WithParameter("Layer", 1)
    //    .WithParameter("Duration", 1f)
    //    .WithContainer("ShowDialogue")
    //    .WithParameter("Character", "Player")
    //    .WithParameter("Dialogue", "Boring as always. What are you cooking? The smell are so good.")
    //    .WithParameter("Append", false)
    //    .WithParameter("Duration", 2f)
    //    .WithParameter("Fade", 1f)
    //    .WithParameter("WaitToComplete", true)
    //    .WithContainer("ShowImage")
    //    .WithParameter("SpriteGroup", "Chapter 01")
    //    .WithParameter("SpriteName", "Frame 07")
    //    .WithParameter("Controller", "Background")
    //    .WithParameter("Layer", 1)
    //    .WithParameter("Duration", 1f)
    //    .WithContainer("ShowDialogue")
    //    .WithParameter("Character", "Player")
    //    .WithParameter("Dialogue", "Just meatballs with steamed vegetables and that seasoning you like.")
    //    .WithParameter("Append", false)
    //    .WithParameter("Duration", 2f)
    //    .WithParameter("Fade", 1f)
    //    .WithParameter("WaitToComplete", true)
    //     .WithContainer("ShowImage")
    //    .WithParameter("SpriteGroup", "Chapter 01")
    //    .WithParameter("SpriteName", "Frame 08")
    //    .WithParameter("Controller", "Background")
    //    .WithParameter("Layer", 1)
    //    .WithParameter("Duration", 1f)
    //    .WithContainer("ShowDialogue")
    //    .WithParameter("Character", "Player")
    //    .WithParameter("Dialogue", "I like your meatballs as much as I hope you like mine. And what you planning to eat?")
    //    .WithParameter("Append", false)
    //    .WithParameter("Duration", 2f)
    //    .WithParameter("Fade", 1f)
    //    .WithParameter("WaitToComplete", true)
    //    .WithContainer("ShowImage")
    //    .WithParameter("SpriteGroup", "Chapter 01")
    //    .WithParameter("SpriteName", "Frame 09")
    //    .WithParameter("Controller", "Background")
    //    .WithParameter("Layer", 1)
    //    .WithParameter("Duration", 1f)
    //    .WithContainer("ShowDialogue")
    //    .WithParameter("Character", "Aisley")
    //    .WithParameter("Dialogue", "Maybe something more 'milky', later. But only after you take a shower and eat well. I don't want to suck on a stinky bottle. The milk don't turn in a way that I like.")
    //    .WithParameter("Append", false)
    //    .WithParameter("Duration", 2f)
    //    .WithParameter("Fade", 1f)
    //    .WithParameter("WaitToComplete", true)
    //    .WithContainer("ShowImage")
    //    .WithParameter("SpriteGroup", "Chapter 01")
    //    .WithParameter("SpriteName", "Frame 10")
    //    .WithParameter("Controller", "Background")
    //    .WithParameter("Layer", 1)
    //    .WithParameter("Duration", 1f)
    //    .WithContainer("ShowDialogue")
    //    .WithParameter("Character", "Aisley")
    //    .WithParameter("Dialogue", "Fill your stomach and later I´ll handle with this little boy.")
    //    .WithParameter("Append", false)
    //    .WithParameter("Duration", 2f)
    //    .WithParameter("Fade", 1f)
    //    .WithParameter("WaitToComplete", true)
    //    .WithContainer("ShowImage")
    //    .WithParameter("SpriteGroup", "Chapter 01")
    //    .WithParameter("SpriteName", "Frame 11")
    //    .WithParameter("Controller", "Background")
    //    .WithParameter("Layer", 1)
    //    .WithParameter("Duration", 1f)
    //    .WithContainer("ShowDialogue")
    //    .WithParameter("Character", "Player")
    //    .WithParameter("Dialogue", "You are the most marvelous thing that a man could desire in this world.")
    //    .WithParameter("Append", false)
    //    .WithParameter("Duration", 2f)
    //    .WithParameter("Fade", 1f)
    //    .WithParameter("WaitToComplete", true)
    //    .Build();

    //    //.WithContainer("ShowMessage")
    //    //.WithParameter("MessageType", "FullMessage")
    //    //.WithParameter("Message", MessageIntro)
    //    //.WithParameter("Append", false)
    //    //.WithParameter("Duration", 2f)
    //    //.WithParameter("Fade", 1f)
    //    //.WithParameter("WaitToComplete", true)
    //    //.WithContainer("ShowDialogue")
    //    //.WithContainer("ShowImage")
    //    //.WithParameter("SpriteGroup", "Chapter 00 (Test)")
    //    //.WithParameter("SpriteName", "Intro00")
    //    //.WithParameter("Controller", "Background")
    //    //.WithParameter("Layer", 1)
    //    //.WithParameter("Duration", 1f)
    //    //.WithContainer("ShowDialogue")
    //    //.WithParameter("Character", "System")
    //    //.WithParameter("Dialogue", "I am sure you as.")
    //    //.WithParameter("Append", false)
    //    //.WithParameter("Duration", 2f)
    //    //.WithParameter("Fade", 1f)
    //    //.WithParameter("WaitToComplete", true)
    //    //.WithContainer("ShowImage")
    //    //.WithParameter("SpriteGroup", "Chapter 00 (Test)")
    //    //.WithParameter("SpriteName", "Intro01")
    //    //.WithParameter("Controller", "Background")
    //    //.WithParameter("Layer", 1)
    //    //.WithParameter("Duration", 1f)
    //    //.WithContainer("ShowDialogue")
    //    //.WithParameter("Character", "System")
    //    //.WithParameter("Dialogue", "Do you think that they will like us?")
    //    //.WithParameter("Append", false)
    //    //.WithParameter("Duration", 2f)
    //    //.WithParameter("Fade", 1f)
    //    //.WithParameter("WaitToComplete", true)
    //    //.WithContainer("ShowImage")
    //    //.WithParameter("SpriteGroup", "Chapter 00 (Test)")
    //    //.WithParameter("SpriteName", "Intro02")
    //    //.WithParameter("Controller", "Background")
    //    //.WithParameter("Layer", 1)
    //    //.WithParameter("Duration", 1f)
    //    //.WithContainer("ShowDialogue")
    //    //.WithParameter("Character", "System")
    //    //.WithParameter("Dialogue", "Sure that. Unless they are those \"21 thousand dollars Magic: The Gathering deckbuilders\"")
    //    //.WithParameter("Append", false)
    //    //.WithParameter("Duration", 2f)
    //    //.WithParameter("Fade", 1f)
    //    //.WithParameter("WaitToComplete", true)
    //    //.WithContainer("ShowInput", new GSC_StringParameter("Name","Aldo",false))
    //    //.WithParameter("Description", "To start, please enter your name")
    //    //.WithParameter("Duration", 2f)
    //    //.WithParameter("Fade", 1f)
    //    //.WithParameter("System",true)
    //    //.WithScene(3)

        
    //}

   

}
